export const SET_PLAY = 'player/play'
export const SET_VOLUME = 'player/volume'
export const SET_SRC = 'player/src'
export const SET_LRC = 'player/lrc'
export const SET_CURRENT = 'player/time'
export const SET_PLAYER = 'player/playerinfo'
export const SET_LIST = 'player/list'